import type { ChatMessage } from "../types";

/**
 * Chat runs on Stream Video custom events (no separate Chat subscription).
 * This service mirrors messages to localStorage so a .txt transcript can be
 * downloaded after the session ends — even if the drawer was closed.
 */

const key = (callId: string) => `ss.transcript.${callId}`;

export function loadTranscript(callId: string): ChatMessage[] {
  try {
    const raw = localStorage.getItem(key(callId));
    return raw ? (JSON.parse(raw) as ChatMessage[]) : [];
  } catch {
    return [];
  }
}

export function saveTranscript(callId: string, messages: ChatMessage[]): void {
  try {
    localStorage.setItem(key(callId), JSON.stringify(messages.slice(-500)));
  } catch {
    /* non-fatal */
  }
}

export function buildTranscriptText(
  meta: { callId: string; startedAt: number | null; endedAt: number; participants: string[] },
  messages: ChatMessage[],
): string {
  const line = "─".repeat(56);
  const fmt = (ts: number) => new Date(ts).toLocaleTimeString("en-IN", { hour12: false });
  const dur = meta.startedAt
    ? Math.max(0, Math.round((meta.endedAt - meta.startedAt) / 1000))
    : 0;
  const mm = String(Math.floor(dur / 60)).padStart(2, "0");
  const ss = String(dur % 60).padStart(2, "0");
  return [
    "SKILLSIGNAL SESSIONS — TRANSCRIPT",
    line,
    `Call         : ${meta.callId}`,
    `Date         : ${new Date(meta.endedAt).toLocaleDateString("en-IN")}`,
    `Duration     : ${mm}:${ss}`,
    `Participants : ${meta.participants.join(", ") || "—"}`,
    `Messages     : ${messages.length}`,
    line,
    "",
    ...messages.map(
      (m) =>
        `[${fmt(m.ts)}] ${m.senderName} (${m.role.toUpperCase()})${m.own ? " [you]" : ""}: ${m.text}`,
    ),
    "",
    line,
    "Generated by SkillSignal Sessions · getstream.io video",
    "",
  ].join("\n");
}

export function downloadTranscript(filename: string, text: string): void {
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 2000);
}
